### ISSUE TITLE
missing composants

### ISSUE THREAD

**Issue by jerome7619** [kborkowski/kborkowski#1]
![memory_game_kborkowski](https://github.com/kborkowski/kborkowski/assets/106749295/91f5f762-e5d5-4120-923f-3f578edf0e19)
Hi, after reading your LinkedIn post, i decided to give a try to your memory game. I imported the zip file without problem and used it without any problem but on the Power Apps main screen i got a error message telling : impossible to load code composants : theppd_ppd.FontImport. Can you tell if something is missing in the zip file or you used a custom font that could be replaced to a standard one ? Other than that, it work nice and loved using it. You should put a reference to you as a copyright reference that link to your website or email address. 
Yours,
Jerome

**Comment by kborkowski** [comment]
Hi @jerome7619 , you can try to import that version of the app where I replaced all the custom fonts with Lato Black: [No pcf version here](https://github.com/kborkowski/powerapps/files/14472379/MemoryGame_20240303093817.zip)
